# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[ ](bg:244) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"

[status]
format = '[$symbol $common_meaning$signal_name$maybe_int ]($style)'
style = "bright-red"
disabled = false
map_symbol = true
symbol = "x"
success_symbol = ""
not_executable_symbol = "/"
not_found_symbol = "?"
sigint_symbol = "x"
signal_symbol = "s"
pipestatus = true
pipestatus_separator = '[|]($style)'
pipestatus_format = '[\[]($style)$pipestatus[\] => $symbol $common_meaning$signal_name$maybe_int ]($style)'
pipestatus_segment_format = '[$symbol $common_meaning$signal_name$maybe_int]($style)'

[shell]
disabled = false
style = "blue"

[cmd_duration]
style = "yellow"

[shlvl]
style = "yellow"
symbol = "_"
disabled = false
threshold = 2

[jobs]
format = '[\[$symbol$number\]]($style) '
symbol = "+"
style = "blue"

[username]
style_root = "bright-red"
style_user = "bright-yellow"

[hostname]
style = "bright-green"

[directory]
read_only = " ro"
style = "cyan"

[git_branch]
symbol = "git "
style = "bright-purple"

[git_commit]
tag_symbol = " tag "
style = "bright-green"

[git_state]
style = "bright-yellow"

[git_metrics]
disabled = false
added_style = "bright-green"
deleted_style = "bright-red"

[git_status]
# ahead = "^${count}"
# behind = "v${count}"
# diverged = "<>^${ahead_count}v${behind_count}"
ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
# renamed = "r"
renamed = "»"
deleted = "x"
style = "bright-red"

[custom.git_lock]
when = 'test -f "$(git rev-parse --git-dir 2> /dev/null)"/index.lock'
require_repo = true
description = "Show if index.lock exists in the repo"
symbol = ""
style = "bold red"
format = "is [${symbol}LOCKED ]($style)"

[golang]
symbol = "go "
style = "cyan"

[aws]
style = "bold 208"
[aws.region_aliases]
us-east-1 = "va"
us-west-2 = "or"

[azure]
symbol = "az "

[buf]
symbol = "buf "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cpp]
symbol = "C++ "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[container]
symbol = "container "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[gleam]
symbol = "gleam "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[haskell]
symbol = "haskell "

[helm]
symbol = "helm "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nats]
symbol = "nats "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pixi]
symbol = "pixi "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[quarto]
symbol = "quarto "

[raku]
symbol = "raku "

[rlang]
symbol = "r "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
