# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[ ](bg:244) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"

[status]
format = '[$symbol $common_meaning$signal_name$maybe_int ]($style)'
style = "bright-red"
disabled = false
map_symbol = true
symbol = "x"
success_symbol = ""
not_executable_symbol = "/"
not_found_symbol = "?"
sigint_symbol = "x"
signal_symbol = "s"
pipestatus = true
pipestatus_separator = '[|]($style)'
pipestatus_format = '[\[]($style)$pipestatus[\] => $symbol $common_meaning$signal_name$maybe_int ]($style)'
pipestatus_segment_format = '[$symbol $common_meaning$signal_name$maybe_int]($style)'

[shell]
disabled = false
style = "blue"

[cmd_duration]
style = "yellow"

[shlvl]
style = "yellow"
symbol = "_"
disabled = false
threshold = 2

[jobs]
format = '[\[$symbol$number\]]($style) '
symbol = "+"
style = "blue"

[username]
style_root = "bright-red"
style_user = "bright-yellow"

[hostname]
style = "bright-green"

[git_branch]
symbol = "git "
style = "bright-purple"

[git_commit]
tag_symbol = " tag "
style = "bright-green"

[git_state]
style = "bright-yellow"

[git_metrics]
disabled = false
added_style = "bright-green"
deleted_style = "bright-red"

[git_status]
# ahead = "^${count}"
# behind = "v${count}"
# diverged = "<>^${ahead_count}v${behind_count}"
ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
# renamed = "r"
renamed = "»"
deleted = "x"
style = "bright-red"

[aws]
style = "bold 208"
[aws.region_aliases]
us-east-1 = "va"
us-west-2 = "or"

[buf]
symbol = "B "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"
style = "cyan"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[golang]
symbol = "go "
style = "cyan"

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
