# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[ ](bg:244) "

[character]
success_symbol = "[](bold 69)"
error_symbol = "[](bold 69)"
vicmd_symbol = "[](bold 69)"

[status]
style = "bg:57 fg:231 bold"
format = '[ $symbol $common_meaning$signal_name$maybe_int ]($style)'
disabled = false
map_symbol = true
symbol = "✖"
success_symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = "✖"
signal_symbol = ""
pipestatus = true
pipestatus_separator = '[|]($style)'
pipestatus_format = '[ \[]($style)$pipestatus[\] => $symbol $common_meaning$signal_name$maybe_int ]($style)'
pipestatus_segment_format = '[$symbol $common_meaning$signal_name$maybe_int]($style)'

[shell]
fish_indicator = "><\\(\\(\\(°>"
powershell_indicator = "_"
xonsh_indicator = "🐚"
zsh_indicator = ""
bash_indicator = "B"
unknown_indicator = "???"
disabled = false
format = "[  $indicator  ](bold fg:231 bg:69)"

[battery]
format = "[ $symbol$percentage ]($style)"

[[battery.display]]
threshold = 10
style = "bold bg:red fg:231"

[[battery.display]]
threshold = 30
style = "bold bg:208 fg:231"

[username]
format = "[$user]($style)"
style_user = "bold green"

[hostname]
format = "[@$hostname]($style) in "
style = "bold green"

[directory]
truncation_length = 8
truncation_symbol = ""
read_only = " "

[jobs]
symbol = "+"
format = "[ $symbol$number ]($style)"
style = "bold bg:21 fg:231"

[aws]
style = "bold 208"
symbol = "  "
[aws.region_aliases]
us-east-1 = "va"
us-west-2 = "or"

[conda]
symbol = " "
ignore_base = false

[git_branch]
symbol = " "

[git_metrics]
disabled = false
#format = '([+$added]($added_style)/[-$deleted]($deleted_style) )'

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[buf]
symbol = " "

[c]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "∆ "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[pijul_channel]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "
disabled = false
threshold = 2

[swift]
symbol = "ﯣ "

[spack]
symbol = "🅢 "

